### ISSUE TITLE
“renderer” file not found

### ISSUE THREAD

**Issue by wmk-in-SH** [Locke637/AVGM#1]
When I run to the "run.py" file, the following error occurs during the package import process:
   **_ImportError: cannot import name 'PyGameRenderer' from 'renderer'_**

**Comment by wmk-in-SH** [comment]
Is it because I packed the wrong “renderer” bag? Or is the "renderer" file missing?
**_ModuleNotFoundError: No module named 'renderer'_**

**Comment by Locke637** [comment]
I have removed the irrelevant packages.
